(ns slp.models.tuitionio)

{
    "success": 1,
    "message": "Your portfolio information is up to date",
    "data": {
        "totals": {
            "accounts": 2,
            "loans": 13,
            "minimum_payment": 0,
            "current_balance": 35240,
            "original_balance": 35240,
            "percent_paid": 0,
            "weighted_interest_rate": 0,
            "remaining_lifetime_interest": 0,
            "remaining_lifetime_payment": 35240,
            "incomplete_repayment_options": 0,
            "payment_too_low": true
        },
        "accounts": {
            "29878": {
                "account_id": 29878,
                "nslds_servicer_id": 2,
                "is_linked": 0,
                "is_saved": 1,
                "is_error": 0,
                "start_refresh": 1,
                "yodlee_item_id": 0,
                "name": "Sallie Mae (Department of Education Loan Services)",
                "last_refresh_time": 0,
                "servicer_id": 1089,
                "site_display_name": "Sallie Mae (Department of Education Loan Services)",
                "logo_image": null,
                "phone_number": "888-272-5543",
                "website": "https:\/\/www.salliemae.com\/",
                "balance": 23323,
                "minimum_payment": 0,
                "due_date": 0,
                "loan_count": 10,
                "refresh_status": "SUCCESS",
                "loans": [{
                    "name": "Cornell University",
                    "loan_id": 73579,
                    "account_id": 29878,
                    "loan_type_id": 2,
                    "loan_type_name": "Stafford Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 2712,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73578,
                    "account_id": 29878,
                    "loan_type_id": 2,
                    "loan_type_name": "Stafford Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 4355,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73577,
                    "account_id": 29878,
                    "loan_type_id": 2,
                    "loan_type_name": "Stafford Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 2177,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73576,
                    "account_id": 29878,
                    "loan_type_id": 2,
                    "loan_type_name": "Stafford Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 3155,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73575,
                    "account_id": 29878,
                    "loan_type_id": 2,
                    "loan_type_name": "Stafford Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 1183,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73574,
                    "account_id": 29878,
                    "loan_type_id": 2,
                    "loan_type_name": "Stafford Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 2362,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73573,
                    "account_id": 29878,
                    "loan_type_id": 2,
                    "loan_type_name": "Stafford Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 1968,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73572,
                    "account_id": 29878,
                    "loan_type_id": 5,
                    "loan_type_name": "Stafford Unsubsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 3380,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73571,
                    "account_id": 29878,
                    "loan_type_id": 5,
                    "loan_type_name": "Stafford Unsubsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 1336,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }, {
                    "name": "School Code For Consolidation Loans",
                    "loan_id": 73570,
                    "account_id": 29878,
                    "loan_type_id": 23,
                    "loan_type_name": "Consolidation Subsidized",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 695,
                    "minimum_payment": 0,
                    "account_name": "DEPT OF ED\/SALLIE MAE"
                }],
                "created_at": 1375833455,
                "is_deleted": 0
            },
            "29879": {
                "account_id": 29879,
                "nslds_servicer_id": 49,
                "is_linked": 0,
                "is_saved": 1,
                "is_error": 0,
                "start_refresh": 1,
                "yodlee_item_id": 0,
                "name": "CARNEGIE-MELLON UNIVERSITY",
                "last_refresh_time": 0,
                "servicer_id": 0,
                "site_display_name": null,
                "logo_image": null,
                "phone_number": "Unknown",
                "website": "Unknown",
                "balance": 11917,
                "minimum_payment": 0,
                "due_date": 0,
                "loan_count": 3,
                "refresh_status": "SUCCESS",
                "loans": [{
                    "name": "Carnegie-mellon University",
                    "loan_id": 73582,
                    "account_id": 29879,
                    "loan_type_id": 19,
                    "loan_type_name": "Perkins",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 2939,
                    "minimum_payment": 0,
                    "account_name": "CARNEGIE-MELLON UNIVERSITY"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73581,
                    "account_id": 29879,
                    "loan_type_id": 19,
                    "loan_type_name": "Perkins",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 7879,
                    "minimum_payment": 0,
                    "account_name": "CARNEGIE-MELLON UNIVERSITY"
                }, {
                    "name": "Cornell University",
                    "loan_id": 73580,
                    "account_id": 29879,
                    "loan_type_id": 19,
                    "loan_type_name": "Perkins",
                    "payment_plan_id": 0,
                    "interest_rate": 0,
                    "balance": 1099,
                    "minimum_payment": 0,
                    "account_name": "CARNEGIE-MELLON UNIVERSITY"
                }],
                "created_at": 1375833455,
                "is_deleted": 0
            }
        },
        "user": {
            "user_id": "34011",
            "email": "michael.sitchenko@gmail.com",
            "first_name": "Michael",
            "last_name": "Sitchenko",
            "dob": "19840711",
            "is_old_user": null,
            "is_onboarded": "1",
            "enrollment_status": null,
            "enrollment_status_date": null,
            "scrape_time": "0",
            "calibration": null,
            "plan_state": "INTRO",
            "survey_complete": "0",
            "is_no_surveys": "0",
            "due_date_reminder": "0",
            "due_date_days_before": "0",
            "is_subscribed": "0",
            "plan_reminder_notifications": "0",
            "send_monthly_summaries": "0",
            "is_veteran": "0",
            "campaign_id": "",
            "last_login_time": "1375933287",
            "is_deleted": "0",
            "meracord account number": null,
            "street_address": null,
            "street_address2": null,
            "city": null,
            "state": null,
            "zip": "10002",
            "phone_number": null,
            "payment_state": null,
            "progress_graph_state": "CURRENT",
            "is_graph_notice_dismissed": "0",
            "last_four_ssn": null,
            "created_at": "1375833348",
            "updated_at": "1375933287"
        }
    }
}